apiVersion: wjdskagml541/test
kind: Deployment
metadata:
  name: mavenweb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: mavenweb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: mavenweb
        image: nhjcontainreg.azurecr.io/wjdskagml541/test:#{Build.BuildId}#
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "mavenweb"
---
apiVersion: v1
kind: Service
metadata:
  name: mavenweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mavenweb
